### ISSUE TITLE
Issue with Request parameter

### ISSUE THREAD

**Issue by hardikvi** [orno/route#10]
Following is my directory structure:

![2015-02-12 15-11-40](https://cloud.githubusercontent.com/assets/8565010/6164908/7c95fd10-b2c9-11e4-8d78-60e1169e18c2.png)

Following is my app.php content:

```
ini_set('error_reporting',E_ERROR);
ini_set('display_errors',1);

require_once __DIR__.'/../vendor/autoload.php';
require_once __DIR__.'/../Src/Config/parameter.php';

use Src\Config\ResolveRoute;


$router = new ResolveRoute();
$router->dispatchRequest();
```

Following is my ResolveRoute class:

```
class ResolveRoute {
    
    protected $route;
    
    public function __construct() {
        $this->route = new RouteCollection();
        $this->addRoutes();
    }

    protected function addRoutes(){
        
        $this->route->addRoute('GET', '/app.php/contact/list/{userId}/{token}', 'Src\Controller\ContactController::listAction');
    }
    
    public function dispatchRequest(){
        
        $dispatcher = $this->route->getDispatcher();
        $response = $dispatcher->dispatch($_SERVER['REQUEST_METHOD'], $_SERVER['REQUEST_URI']);
        $response->send();
        
    }
    
}
```

Following is my ContactController class:

```
class ContactController extends BaseController {

    public function listAction(Request $request, Response $response){
        
        print_r($_REQUEST);
        print_r($request);
        
        exit;
        
        if(!$this->authenticateUser($request))
        {
            return $this->throwException ("User not found");
        }

        return new JsonResponse(\Src\Model\ContactRepositroy::getList());
    }

}
```

Now, issue is $_REQUEST and $request is always blank if i set route as :

```
$this->route->addRoute('GET', '/app.php/contact/list/{userId}/{token}', 'Src\Controller\ContactController::listAction');
```

And if i set route as : 

```
$this->route->addRoute('GET', '/app.php/contact/list?userId={userId}&token={token}', 'Src\Controller\ContactController::listAction');
```

Then i am getting parameters in $_REQUEST but $request object is always empty.
Please guide me what is missing by me.

**Comment by philipobenito** [comment]
Firstly I'd recommend swapping out orno/route for league/route as the package has been moved over to The PHP League https://github.com/thephpleague/route

As for your actual issue, and this will be the same when you port over, it's because the Request object hasn't been built and stored in the container so it gives you an empty Request. This could actually be classed as a bug as thinking about it now the router should actually check if the Request exists and create/configure one if it doesn't. That is me making an assumption so I'm sorry about that.

I'll put a gist together today to show you how to do it based on your code as I think that's the simplest way, as part of that I'll use the new league package as there are a couple of small changes.

**Comment by hardikvi** [comment]
Hello @philipobenito,

First of all thank you for the reply.
Please let me know your gist URL here when you are done.

Regards,
Hardik

**Comment by philipobenito** [comment]
@hardikvi not a problem, it will be at some point today, I also plan on creating an example skeleton project which will help in cases like this in the future.

**Comment by hardikvi** [comment]
Hello @philipobenito,

Have you created that example ?

Regards,
Hardik

**Comment by hardikvi** [comment]
Hello @philipobenito,

Have you created that example ?

Regards,
Hardik
